package com.harleystudios.critterextraction;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.LinearGradient;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.RectF;
import android.graphics.Shader;
import android.view.View;

/** Pixel-reference native rendering of the canonical /live match HUD. */
public final class LiveHudOverlay extends View {
    private static final float DW=1536,DH=720;private static final int TEXT=0xfff7f7ff,MUTED=0xffaeb2d1,MINT=0xff7ef7d4,CYAN=0xff63dff5,PURPLE=0xff8e82ff,YELLOW=0xffffd36f,DANGER=0xffff6f91;
    private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG),stroke=new Paint(Paint.ANTI_ALIAS_FLAG);private final Game3DView game;
    public LiveHudOverlay(Context context,Game3DView game){super(context);this.game=game;setWillNotDraw(false);setClickable(false);stroke.setStyle(Paint.Style.STROKE);}
    @Override protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight();if(w<2||h<2)return;float s=Math.min(w/DW,h/DH),ox=(w-DW*s)/2f,oy=(h-DH*s)/2f;c.save();c.translate(ox,oy);c.scale(s,s);drawSquad(c);drawCenter(c);drawMinimap(c);drawVitals(c);drawCrosshair(c);drawQuickbar(c);drawAmmo(c);drawTouchGuides(c);drawPrompt(c);c.restore();postInvalidateOnAnimation();}
    private void drawSquad(Canvas c){RectF r=new RectF(16,14,310,86);panel(c,r,0xb30a0b1b,13,0x33ffffff);circle(c,45,43,19,PURPLE);String species=game.speciesName();text(c,species.substring(0,Math.min(2,species.length())).toUpperCase(),45,48,10,0xff111225,Paint.Align.CENTER,true);text(c,species,72,39,14,TEXT,Paint.Align.LEFT,true);String net=game.networkMode();if(net==null||net.isEmpty())net="SOLO";text(c,net+" • "+game.networkPlayers()+"/4",72,57,9,MINT,Paint.Align.LEFT,true);RectF hp=new RectF(72,66,294,75);round(c,hp,0xff111328,6);p.setShader(new LinearGradient(hp.left,0,hp.right,0,DANGER,0xffffb27d,Shader.TileMode.CLAMP));c.drawRoundRect(new RectF(hp.left,hp.top,hp.left+hp.width()*clamp(game.hp()/100f,0,1),hp.bottom),6,6,p);p.setShader(null);}
    private void drawCenter(Canvas c){float cx=DW/2;RectF compass=new RectF(cx-190,12,cx+190,42);panel(c,compass,0xa00a0b1b,10,0x22ffffff);String[] parts={"W","285","NW","000","N","45","NE"};float x=compass.left+25,step=(compass.width()-50)/(parts.length-1);for(int i=0;i<parts.length;i++)text(c,parts[i],x+i*step,32,i==3?12:9,i==3?TEXT:MUTED,Paint.Align.CENTER,i==3);RectF obj=new RectF(cx-270,50,cx+270,118);panel(c,obj,0xc90a0b1b,13,0x33ffffff);text(c,game.primaryComplete()?game.loot()>=5?"STEP 3":"STEP 2":"STEP 1",obj.left+15,obj.top+18,9,MINT,Paint.Align.LEFT,true);text(c,game.objectiveTitle(),obj.left+15,obj.top+40,13,TEXT,Paint.Align.LEFT,true);text(c,game.objectiveDetail(),obj.left+15,obj.top+58,9,MUTED,Paint.Align.LEFT,false);text(c,"DROP CLOSES",cx+82,obj.top+18,8,MUTED,Paint.Align.CENTER,true);text(c,time(game.matchSeconds()),cx+82,obj.top+47,22,TEXT,Paint.Align.CENTER,true);text(c,"MOONBERRIES",obj.right-65,obj.top+18,8,MUTED,Paint.Align.CENTER,true);text(c,game.loot()+" / 5",obj.right-65,obj.top+46,19,YELLOW,Paint.Align.CENTER,true);RectF tag=new RectF(cx-70,125,cx+70,148);panel(c,tag,0xa00a0b1b,8,0x22ffffff);text(c,game.cameraName()+" • "+(game.shoulderRight()?"R":"L"),cx,141,8,0xffd9dbef,Paint.Align.CENTER,true);}
    private void drawMinimap(Canvas c){RectF card=new RectF(1278,92,1521,342);panel(c,card,0xc00a0b1b,15,0x33ffffff);text(c,game.mapName(),1292,114,10,TEXT,Paint.Align.LEFT,true);RectF map=new RectF(1290,124,1509,244);round(c,map,0xff17353b,10);stroke.setColor(0x665fd0c0);stroke.setStrokeWidth(5);c.drawLine(map.left+20,map.bottom-18,map.right-18,map.top+25,stroke);stroke.setColor(0x557f89a9);stroke.setStrokeWidth(3);c.drawLine(map.centerX(),map.top,map.centerX(),map.bottom,stroke);float px=map.centerX()+clamp(game.playerX()/NativeMatch.WORLD,-1,1)*map.width()*.45f,pz=map.centerY()+clamp(game.playerZ()/NativeMatch.WORLD,-1,1)*map.height()*.45f;triangle(c,px,pz,7,CYAN);float ex=map.centerX()+clamp(game.extractX()/NativeMatch.WORLD,-1,1)*map.width()*.45f,ez=map.centerY()+clamp(game.extractZ()/NativeMatch.WORLD,-1,1)*map.height()*.45f;diamond(c,ex,ez,7,YELLOW);text(c,"PLAYERS "+game.networkPlayers()+"/4",map.right-6,114,9,MINT,Paint.Align.RIGHT,true);text(c,"DROP OBJECTIVES",1292,266,9,MINT,Paint.Align.LEFT,true);text(c,(game.primaryComplete()?"✓ ":"◇ ")+game.primaryTitle(),1292,285,9,game.primaryComplete()?MINT:TEXT,Paint.Align.LEFT,false);text(c,(game.bonusComplete()?"✓ ":"◇ ")+game.bonusTitle()+"  BONUS",1292,303,9,game.bonusComplete()?MINT:MUTED,Paint.Align.LEFT,false);text(c,(game.loot()>=5?"✓ ":"◇ ")+"Collect Moonberries  "+game.loot()+" / 5",1292,321,9,game.loot()>=5?MINT:MUTED,Paint.Align.LEFT,false);text(c,"◇ Extract alive",1292,338,9,game.primaryComplete()&&game.loot()>=5?TEXT:MUTED,Paint.Align.LEFT,false);}
    private void drawVitals(Canvas c){RectF box=new RectF(18,604,286,700);panel(c,box,0xb60a0b1b,14,0x33ffffff);text(c,"HEALTH",31,626,9,MUTED,Paint.Align.LEFT,true);RectF hp=new RectF(31,635,273,650);round(c,hp,0xff251526,8);round(c,new RectF(hp.left,hp.top,hp.left+hp.width()*clamp(game.hp()/100f,0,1),hp.bottom),DANGER,8);text(c,Math.round(game.hp())+"",273,629,11,TEXT,Paint.Align.RIGHT,true);text(c,"SHIELD",31,673,9,MUTED,Paint.Align.LEFT,true);RectF sh=new RectF(31,681,273,696);round(c,sh,0xff101a2a,8);round(c,new RectF(sh.left,sh.top,sh.left+sh.width()*clamp(game.shield()/75f,0,1),sh.bottom),CYAN,8);text(c,Math.round(game.shield())+"",273,675,11,TEXT,Paint.Align.RIGHT,true);}
    private void drawCrosshair(Canvas c){float cx=DW/2,cy=DH/2;stroke.setColor(0xffffffff);stroke.setStrokeWidth(2);c.drawLine(cx-16,cy,cx-6,cy,stroke);c.drawLine(cx+6,cy,cx+16,cy,stroke);c.drawLine(cx,cy-16,cx,cy-6,stroke);c.drawLine(cx,cy+6,cx,cy+16,stroke);circle(c,cx,cy,2,0xffffffff);}
    private void drawQuickbar(Canvas c){float cx=DW/2,y=657,slot=44,gap=6,total=slot*5+gap*4,x=cx-total/2;for(int i=0;i<5;i++){RectF r=new RectF(x+i*(slot+gap),y,x+i*(slot+gap)+slot,y+slot);panel(c,r,i==0?0x555fdff5:0xb00a0b1b,9,i==0?0xaa63dff5:0x33ffffff);text(c,""+(i+1),r.left+6,r.top+11,8,MUTED,Paint.Align.LEFT,true);if(i==0)text(c,"●",r.centerX(),r.centerY()+7,17,MINT,Paint.Align.CENTER,true);if(i==1)text(c,"+",r.centerX(),r.centerY()+8,20,0xffffb4c5,Paint.Align.CENTER,true);}}
    private void drawAmmo(Canvas c){RectF r=new RectF(1340,625,1518,704);panel(c,r,0xc00a0b1b,12,0x33ffffff);text(c,game.weaponName().toUpperCase(),r.right-12,r.top+20,9,MUTED,Paint.Align.RIGHT,true);text(c,game.magazine()+" / "+game.reserveAmmo(),r.right-12,r.top+53,27,TEXT,Paint.Align.RIGHT,true);text(c,"AMMO",r.left+12,r.bottom-11,8,YELLOW,Paint.Align.LEFT,true);}
    private void drawTouchGuides(Canvas c){stroke.setColor(0x667ef7d4);stroke.setStrokeWidth(2);c.drawCircle(105,520,55,stroke);c.drawCircle(105,520,23,stroke);text(c,"MOVE",105,590,9,MINT,Paint.Align.CENTER,true);RectF look=new RectF(835,320,1260,602);stroke.setColor(0x2263dff5);stroke.setStrokeWidth(1);c.drawRoundRect(look,16,16,stroke);text(c,"DRAG TO LOOK",look.centerX(),look.top+20,9,0x7763dff5,Paint.Align.CENTER,true);}
    private void drawPrompt(Canvas c){String prompt=game.interactionHint();if(prompt!=null&&!prompt.isEmpty()){RectF r=new RectF(DW/2-130,565,DW/2+130,602);panel(c,r,0xd0111225,12,0x668e82ff);text(c,prompt,r.centerX(),r.centerY()+6,13,TEXT,Paint.Align.CENTER,true);}String banner=game.banner();if(banner!=null&&!banner.isEmpty()){RectF r=new RectF(DW/2-190,165,DW/2+190,201);panel(c,r,0xd0111225,10,0x667ef7d4);text(c,banner,r.centerX(),r.centerY()+6,12,MINT,Paint.Align.CENTER,true);}}
    private String time(float sec){int s=Math.max(0,Math.round(sec));return String.format(java.util.Locale.US,"%02d:%02d",s/60,s%60);}private void triangle(Canvas c,float x,float y,float s,int col){Path q=new Path();q.moveTo(x,y-s);q.lineTo(x-s*.72f,y+s);q.lineTo(x+s*.72f,y+s);q.close();p.setColor(col);c.drawPath(q,p);}private void diamond(Canvas c,float x,float y,float s,int col){Path q=new Path();q.moveTo(x,y-s);q.lineTo(x+s,y);q.lineTo(x,y+s);q.lineTo(x-s,y);q.close();p.setColor(col);c.drawPath(q,p);}private void circle(Canvas c,float x,float y,float radius,int color){p.setShader(null);p.setColor(color);p.setStyle(Paint.Style.FILL);c.drawCircle(x,y,radius,p);}private void panel(Canvas c,RectF r,int color,float radius,int border){round(c,r,color,radius);stroke.setColor(border);stroke.setStrokeWidth(1);c.drawRoundRect(r,radius,radius,stroke);}private void round(Canvas c,RectF r,int color,float radius){p.setShader(null);p.setColor(color);p.setStyle(Paint.Style.FILL);c.drawRoundRect(r,radius,radius,p);}private void text(Canvas c,String s,float x,float y,float size,int color,Paint.Align align,boolean bold){p.setShader(null);p.setColor(color);p.setTextSize(size);p.setTextAlign(align);p.setTypeface(android.graphics.Typeface.create("sans",bold?android.graphics.Typeface.BOLD:android.graphics.Typeface.NORMAL));c.drawText(s==null?"":s,x,y,p);}private float clamp(float v,float lo,float hi){return Math.max(lo,Math.min(hi,v));}
}
