package com.harleystudios.critterextraction;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.pm.ActivityInfo;
import android.graphics.Bitmap;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputFilter;
import android.text.InputType;
import android.view.Gravity;
import android.view.MotionEvent;
import android.view.View;
import android.view.WindowInsets;
import android.view.WindowInsetsController;
import android.widget.Button;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import java.util.List;

/** Fully native Android shell for the /live game systems. No WebView is created. */
public final class MainActivity extends Activity {
    private static final int TEXT=0xfff7f7ff,MUTED=0xffaeb2d1,MINT=0xff7ef7d4,CYAN=0xff63dff5,PURPLE=0xff8e82ff;
    private NativeProfileStore store;private Game3DView gameView;private FrameLayout gameRoot;private LiveMenuView menuView;private NativeMultiplayerManager network;private AlertDialog lobbyDialog;
    @Override protected void onCreate(Bundle b){super.onCreate(b);try{setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE);}catch(Throwable ignored){}store=new NativeProfileStore(this);enterImmersiveModeSafely();if(store.hasAccounts())showMenu();else showFirstRunAccount();}

    private void showFirstRunAccount(){
        LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setGravity(Gravity.CENTER_HORIZONTAL);panel.setPadding(dp(30),dp(22),dp(30),dp(28));panel.setBackgroundColor(0xff111225);
        ImageView logo=new ImageView(this);Bitmap icon=new AssetLibrary(this).renderSvg("branding/icon.svg",512);if(icon!=null)logo.setImageBitmap(icon);logo.setContentDescription("Critter Extraction puppy logo");panel.addView(logo,new LinearLayout.LayoutParams(dp(150),dp(150)));
        TextView eyebrow=label("HARLEY’S STUDIOS PRESENTS",12,MINT,true);eyebrow.setGravity(Gravity.CENTER);panel.addView(eyebrow);
        TextView title=label("Create Your Critter Account",28,TEXT,true);title.setGravity(Gravity.CENTER);panel.addView(title);
        TextView help=label("Your profile, stash, loadouts, Petals, settings, and career stay separate on this device. No default rookie account will be created.",13,MUTED,false);help.setGravity(Gravity.CENTER);help.setMaxWidth(dp(640));panel.addView(help);
        EditText display=accountField("Display name",24,false),username=accountField("Username",20,false),bio=accountField("Bio (optional)",90,true);panel.addView(display,new LinearLayout.LayoutParams(-1,-2));panel.addView(username,new LinearLayout.LayoutParams(-1,-2));panel.addView(bio,new LinearLayout.LayoutParams(-1,-2));
        Button create=lobbyButton("Create Device Account");LinearLayout.LayoutParams createLayout=new LinearLayout.LayoutParams(-1,dp(54));createLayout.topMargin=dp(14);panel.addView(create,createLayout);
        create.setOnClickListener(v->{String name=display.getText().toString().trim(),handle=username.getText().toString().trim().replaceFirst("^@","");if(name.length()<2){display.setError("Enter at least 2 characters.");return;}if(!handle.matches("[A-Za-z0-9_.-]{3,20}")){username.setError("Use 3–20 letters, numbers, dots, dashes, or underscores.");return;}store.createAccount(name,handle,bio.getText().toString());showMenu();});
        setContentView(scroll(panel));
    }

    private EditText accountField(String hint,int max,boolean multiline){EditText field=new EditText(this);field.setHint(hint);field.setTextColor(TEXT);field.setHintTextColor(MUTED);field.setSingleLine(!multiline);field.setMaxLines(multiline?3:1);field.setFilters(new InputFilter[]{new InputFilter.LengthFilter(max)});field.setPadding(dp(14),dp(10),dp(14),dp(10));return field;}

    private void showMenu(){closeLobbyDialog();closeNetwork();if(gameView!=null){try{gameView.pauseForLifecycle();}catch(Throwable ignored){}gameView=null;}gameRoot=null;menuView=new LiveMenuView(this,store);menuView.setListener(new LiveMenuView.Listener(){public void onPlaySolo(){showGame(null);}public void onHost(){chooseHostMode();}public void onJoin(){askJoinCode();}public void onControls(){NativeGameDialogs.controls(MainActivity.this);}public void onSettings(){NativeGameDialogs.settings(MainActivity.this,store,MainActivity.this::refreshMenu);}public void onTradingPost(){NativeGameDialogs.merchant(MainActivity.this,store,MainActivity.this::refreshMenu);}public void onAccount(){showAccountActions();}public void onEditProfile(){NativeGameDialogs.profile(MainActivity.this,store,MainActivity.this::refreshMenu);}public void onAccounts(){NativeGameDialogs.accounts(MainActivity.this,store,MainActivity.this::refreshMenu);}public void onLoadout(){NativeGameDialogs.loadouts(MainActivity.this,store,MainActivity.this::refreshMenu);}public void onStash(){NativeGameDialogs.stash(MainActivity.this,store,MainActivity.this::refreshMenu);}public void onCharacter(){NativeGameDialogs.character(MainActivity.this,store,MainActivity.this::refreshMenu);}});setContentView(menuView);}
    private void refreshMenu(){if(menuView!=null)menuView.refresh();}
    private void showAccountActions(){String[] actions={"Name & Profile","Switch / Manage Accounts","Character","Portable Save"};new AlertDialog.Builder(this).setTitle(store.active().displayName).setItems(actions,(d,w)->{if(w==0)NativeGameDialogs.profile(this,store,this::refreshMenu);else if(w==1)NativeGameDialogs.accounts(this,store,this::refreshMenu);else if(w==2)NativeGameDialogs.character(this,store,this::refreshMenu);else NativeGameDialogs.saveTools(this,store,this::refreshMenu);}).setNegativeButton("Cancel",null).show();}

    private void chooseHostMode(){new AlertDialog.Builder(this).setTitle("Host Multiplayer").setMessage("Choose how this direct room handles player combat.").setPositiveButton("Co-op",(d,w)->openHostLobby("coop")).setNegativeButton("PvP",(d,w)->openHostLobby("pvp")).setNeutralButton("Cancel",null).show();}
    private void openHostLobby(String mode){closeNetwork();network=new NativeMultiplayerManager(this,store);LinearLayout box=lobbyBox();TextView code=label("ROOM CODE\nCreating…",26,MINT,true),status=label("Connecting…",13,MUTED,false),peers=label("1 / 4 critters",13,TEXT,true);box.addView(code);box.addView(status);box.addView(peers);Button start=lobbyButton("Start Drop");start.setEnabled(false);box.addView(start);Button cancel=lobbyButton("Cancel Room");box.addView(cancel);NativeMultiplayerManager mgr=network;String room=mgr.host(mode,new NativeMultiplayerManager.Listener(){public void onStatus(String s){status.setText(s);code.setText("ROOM CODE\n"+mgr.roomCode());start.setEnabled(true);}public void onPeerCount(int n){peers.setText(n+" / 4 critters • "+mode.toUpperCase());}public void onGameStart(long seed){closeLobbyDialogOnly();showGame(mgr);}public void onError(String e){status.setText(e);Toast.makeText(MainActivity.this,e,Toast.LENGTH_LONG).show();}});code.setText("ROOM CODE\n"+room);start.setOnClickListener(v->mgr.startGame());cancel.setOnClickListener(v->{closeLobbyDialog();closeNetwork();});lobbyDialog=new AlertDialog.Builder(this).setTitle("Direct Room • "+mode.toUpperCase()).setView(scroll(box)).setCancelable(false).create();lobbyDialog.show();}
    private void askJoinCode(){EditText code=new EditText(this);code.setHint("6-digit room code");code.setInputType(InputType.TYPE_CLASS_NUMBER);code.setFilters(new InputFilter[]{new InputFilter.LengthFilter(6)});code.setTextColor(TEXT);code.setHintTextColor(MUTED);new AlertDialog.Builder(this).setTitle("Join Multiplayer").setView(code).setNegativeButton("Cancel",null).setPositiveButton("Join",(d,w)->openJoinLobby(code.getText().toString())).show();}
    private void openJoinLobby(String room){closeNetwork();network=new NativeMultiplayerManager(this,store);LinearLayout box=lobbyBox();TextView code=label("ROOM CODE\n"+room,26,MINT,true),status=label("Finding host…",13,MUTED,false),peers=label("Connecting direct WebRTC…",13,TEXT,true);box.addView(code);box.addView(status);box.addView(peers);Button cancel=lobbyButton("Cancel Join");box.addView(cancel);NativeMultiplayerManager mgr=network;mgr.join(room,new NativeMultiplayerManager.Listener(){public void onStatus(String s){status.setText(s);}public void onPeerCount(int n){peers.setText(n+" / 4 critters connected");}public void onGameStart(long seed){closeLobbyDialogOnly();showGame(mgr);}public void onError(String e){status.setText(e);Toast.makeText(MainActivity.this,e,Toast.LENGTH_LONG).show();}});cancel.setOnClickListener(v->{closeLobbyDialog();closeNetwork();});lobbyDialog=new AlertDialog.Builder(this).setTitle("Joining Direct Room").setView(scroll(box)).setCancelable(false).create();lobbyDialog.show();}
    private LinearLayout lobbyBox(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(12),dp(18),dp(12));box.setBackgroundColor(0xff202344);return box;}private Button lobbyButton(String text){Button b=new Button(this);b.setText(text);b.setAllCaps(false);b.setTextColor(TEXT);b.setBackgroundColor(PURPLE);return b;}
    private void closeLobbyDialog(){closeLobbyDialogOnly();}private void closeLobbyDialogOnly(){if(lobbyDialog!=null){try{lobbyDialog.dismiss();}catch(Throwable ignored){}lobbyDialog=null;}}private void closeNetwork(){if(network!=null){try{network.close();}catch(Throwable ignored){}network=null;}}

    private void showGame(NativeMultiplayerManager net){try{menuView=null;gameRoot=new FrameLayout(this);gameRoot.setBackgroundColor(0xff111225);gameView=new Game3DView(this,store,net);gameView.setResultListener((extracted,summary)->runOnUiThread(()->showResults(extracted,summary)));gameRoot.addView(gameView,new FrameLayout.LayoutParams(-1,-1));gameRoot.addView(new LiveHudOverlay(this,gameView),new FrameLayout.LayoutParams(-1,-1));addTouchControls(gameRoot);setContentView(gameRoot);gameView.resumeGameLoop();}catch(Throwable e){showStartupFailure(e);}}
    private void addTouchControls(FrameLayout root){float s=referenceScale();int top=px(10,s),right=px(14,s);addButton(root,"Ⅱ",Gravity.TOP|Gravity.RIGHT,right,top,44,38,s,v->showPause());right+=px(50,s);addButton(root,"BAG",Gravity.TOP|Gravity.RIGHT,right,top,54,38,s,v->showMatchInventory());right+=px(60,s);addButton(root,"CAM",Gravity.TOP|Gravity.RIGHT,right,top,54,38,s,v->gameView.toggleCamera());right+=px(60,s);addButton(root,"↔",Gravity.TOP|Gravity.RIGHT,right,top,44,38,s,v->gameView.toggleShoulder());right+=px(50,s);addButton(root,"JUMP",Gravity.TOP|Gravity.RIGHT,right,top,64,38,s,v->gameView.jump());int bottom=px(16,s);right=px(14,s);Button fire=addButton(root,"FIRE",Gravity.BOTTOM|Gravity.RIGHT,right,bottom,76,76,s,null);hold(fire,v->gameView.setFire(v));right+=px(84,s);Button aim=addButton(root,"AIM",Gravity.BOTTOM|Gravity.RIGHT,right,bottom+px(8,s),60,60,s,null);hold(aim,v->gameView.setAim(v));right+=px(68,s);Button use=addButton(root,"USE",Gravity.BOTTOM|Gravity.RIGHT,right,bottom+px(8,s),60,60,s,null);hold(use,v->gameView.setUse(v));right+=px(68,s);addButton(root,"+",Gravity.BOTTOM|Gravity.RIGHT,right,bottom+px(8,s),54,54,s,v->gameView.heal());right+=px(61,s);addButton(root,"R",Gravity.BOTTOM|Gravity.RIGHT,right,bottom+px(8,s),54,54,s,v->gameView.reload());right+=px(61,s);addButton(root,"C",Gravity.BOTTOM|Gravity.RIGHT,right,bottom+px(8,s),54,54,s,v->gameView.crouch());}
    private interface Hold{void set(boolean v);}private void hold(Button b,Hold h){b.setOnTouchListener((v,e)->{if(e.getActionMasked()==MotionEvent.ACTION_DOWN){h.set(true);v.setPressed(true);return true;}if(e.getActionMasked()==MotionEvent.ACTION_UP||e.getActionMasked()==MotionEvent.ACTION_CANCEL){h.set(false);v.setPressed(false);return true;}return true;});}
    private Button addButton(FrameLayout root,String text,int gravity,int side,int vertical,float width,float height,float scale,View.OnClickListener click){Button b=new Button(this);b.setText(text);b.setAllCaps(false);b.setTextColor(TEXT);b.setTextSize(10);b.setPadding(0,0,0,0);b.setMinHeight(0);b.setMinWidth(0);b.setBackground(panel(0xc00a0b1b,12,0x66ffffff));if(click!=null)b.setOnClickListener(click);FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(px(width,scale),px(height,scale),gravity);if((gravity&Gravity.RIGHT)==Gravity.RIGHT)lp.rightMargin=side;else lp.leftMargin=side;if((gravity&Gravity.BOTTOM)==Gravity.BOTTOM)lp.bottomMargin=vertical;else lp.topMargin=vertical;root.addView(b,lp);return b;}

    private void showMatchInventory(){if(gameView==null)return;gameView.pauseForLifecycle();LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),dp(12),dp(16),dp(12));box.setBackgroundColor(0xff202344);box.addView(label("MATCH BACKPACK",12,MINT,true));box.addView(label(gameView.weaponName()+"   "+gameView.magazine()+" / "+gameView.reserveAmmo()+" ammo\nHealth "+Math.round(gameView.hp())+"   Shield "+Math.round(gameView.shield())+"   Moonberries "+gameView.loot()+" / 5\n"+gameView.networkMode()+" • "+gameView.networkPlayers()+" player(s)",14,TEXT,true));List<NativeProfileStore.Stack> items=gameView.backpack();if(items.isEmpty())box.addView(label("Backpack is empty.",13,MUTED,false));for(NativeProfileStore.Stack st:items){NativeGameData.Item item=NativeGameData.ITEMS.get(st.itemId);box.addView(label((item==null?st.itemId:item.name)+" ×"+st.qty,13,TEXT,false));}box.addView(label("USE picks up world loot and opens nearby supply chests. Extracted non-ammo loot is banked to Account Stash.",11,MUTED,false));AlertDialog d=new AlertDialog.Builder(this).setTitle("Inventory").setView(scroll(box)).setPositiveButton("Resume",null).create();d.setOnDismissListener(x->{if(gameView!=null)gameView.resumeGameLoop();});d.show();}
    private void showPause(){if(gameView==null)return;gameView.pauseForLifecycle();String[] choices={"Resume","Inventory","Controls","Settings","Leave Drop"};AlertDialog d=new AlertDialog.Builder(this).setTitle("Pause Menu").setItems(choices,(dialog,which)->{if(which==0){dialog.dismiss();gameView.resumeGameLoop();}else if(which==1){dialog.dismiss();showMatchInventory();}else if(which==2){NativeGameDialogs.controls(this);gameView.resumeGameLoop();}else if(which==3){NativeGameDialogs.settings(this,store,()->{});gameView.resumeGameLoop();}else{dialog.dismiss();confirmLeave();}}).create();d.setOnCancelListener(x->{if(gameView!=null)gameView.resumeGameLoop();});d.show();}
    private void confirmLeave(){new AlertDialog.Builder(this).setTitle("Leave Drop?").setMessage("Unextracted match loot will be lost, matching the extraction rules.").setNegativeButton("Stay",(d,w)->{if(gameView!=null)gameView.resumeGameLoop();}).setPositiveButton("Leave",(d,w)->showMenu()).show();}
    private void showResults(boolean extracted,String summary){if(gameView!=null)gameView.pauseForLifecycle();NativeProfileStore.Account a=store.active();String message=(extracted?"Extraction successful.":"The drop ended without extraction.")+"\n\n"+summary+"\n\nCareer: "+a.stats.extracts+" extracts • "+a.stats.berries+" berries • "+a.stats.kills+" critters • "+a.stats.matches+" drops\n🌸 "+NativeGameData.formatPetals(a.petals);new AlertDialog.Builder(this).setTitle(extracted?"EXTRACTED":"DROP ENDED").setMessage(message).setCancelable(false).setPositiveButton("Return to Menu",(d,w)->showMenu()).setNegativeButton("New Solo Drop",(d,w)->{closeNetwork();showGame(null);}).show();}

    private ScrollView scroll(View v){ScrollView s=new ScrollView(this);s.setBackgroundColor(0xff111225);s.addView(v);return s;}private TextView label(String text,float sp,int color,boolean bold){TextView t=new TextView(this);t.setText(text);t.setTextSize(sp);t.setTextColor(color);t.setTypeface(android.graphics.Typeface.create("sans",bold?1:0));t.setPadding(0,dp(5),0,dp(5));return t;}private GradientDrawable panel(int color,float radius,int strokeColor){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp((int)radius));g.setStroke(Math.max(1,dp(1)),strokeColor);return g;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private float referenceScale(){android.util.DisplayMetrics m=getResources().getDisplayMetrics();return Math.min(m.widthPixels/1536f,m.heightPixels/720f);}private int px(float v,float s){return Math.max(1,Math.round(v*s));}
    private void enterImmersiveModeSafely(){try{getWindow().setDecorFitsSystemWindows(false);WindowInsetsController c=getWindow().getInsetsController();if(c!=null){c.hide(WindowInsets.Type.statusBars()|WindowInsets.Type.navigationBars());c.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);}}catch(Throwable ignored){getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);}}
    private void showStartupFailure(Throwable error){gameView=null;TextView m=new TextView(this);m.setGravity(Gravity.CENTER);m.setTextColor(Color.WHITE);m.setBackgroundColor(0xff111225);m.setTextSize(18);String t=error==null?"Unknown":error.getClass().getSimpleName();m.setText("CRITTER EXTRACTION\n\nNative OpenGL startup failed.\n"+t+"\n\nScreenshot this screen so this device can be fixed.");m.setPadding(48,48,48,48);setContentView(m);}
    @Override protected void onResume(){super.onResume();enterImmersiveModeSafely();if(gameView!=null)gameView.resumeGameLoop();}@Override protected void onPause(){if(gameView!=null)gameView.pauseForLifecycle();super.onPause();}@Override protected void onDestroy(){closeNetwork();super.onDestroy();}@Override public void onWindowFocusChanged(boolean focus){super.onWindowFocusChanged(focus);if(focus)enterImmersiveModeSafely();}@Override public void onBackPressed(){if(gameView!=null)showPause();else super.onBackPressed();}
}
