package com.harleystudios.critterextraction;

import android.content.Context;
import android.graphics.Color;
import android.opengl.GLES30;
import android.opengl.GLSurfaceView;
import android.opengl.Matrix;

import java.util.ArrayList;
import java.util.List;

/** Native OpenGL ES 3 renderer backed by the canonical NativeMatch simulation. */
public final class Native3DRenderer implements GLSurfaceView.Renderer {
    private final NativeMatch match;private final NativeMultiplayerManager network;
    private volatile boolean running=true;
    private final float[] projection=new float[16],view=new float[16],vp=new float[16],model=new float[16],mvp=new float[16];
    private MeshFactory3D.Mesh cube,sphere,cylinder,cone;private int program,aPos,aNormal,uMvp,uModel,uColor,uCamera,uFogColor;private int width=1,height=1;private long lastNs;
    public Native3DRenderer(Context context,NativeProfileStore store){this(context,store,null);}public Native3DRenderer(Context context,NativeProfileStore store,NativeMultiplayerManager network){this.network=network;long seed=network!=null&&network.matchSeed()!=0?network.matchSeed():System.nanoTime()^(long)store.active().id.hashCode();match=new NativeMatch(context,store,seed);if(network!=null)network.attachMatch(match);}
    public NativeMatch match(){return match;}
    @Override public void onSurfaceCreated(javax.microedition.khronos.opengles.GL10 gl,javax.microedition.khronos.egl.EGLConfig config){GLES30.glEnable(GLES30.GL_DEPTH_TEST);GLES30.glEnable(GLES30.GL_BLEND);GLES30.glBlendFunc(GLES30.GL_SRC_ALPHA,GLES30.GL_ONE_MINUS_SRC_ALPHA);GLES30.glEnable(GLES30.GL_CULL_FACE);GLES30.glCullFace(GLES30.GL_BACK);program=buildProgram(VS,FS);aPos=GLES30.glGetAttribLocation(program,"aPos");aNormal=GLES30.glGetAttribLocation(program,"aNormal");uMvp=GLES30.glGetUniformLocation(program,"uMvp");uModel=GLES30.glGetUniformLocation(program,"uModel");uColor=GLES30.glGetUniformLocation(program,"uColor");uCamera=GLES30.glGetUniformLocation(program,"uCamera");uFogColor=GLES30.glGetUniformLocation(program,"uFogColor");String q=match.account().settings.quality;int lat="high".equals(q)?18:"low".equals(q)?7:12,lon="high".equals(q)?24:"low".equals(q)?10:16,seg="high".equals(q)?18:"low".equals(q)?8:12;sphere=MeshFactory3D.sphere(lat,lon);cube=MeshFactory3D.cube();cylinder=MeshFactory3D.cylinder(seg);cone=MeshFactory3D.cone(seg);lastNs=0;}
    @Override public void onSurfaceChanged(javax.microedition.khronos.opengles.GL10 gl,int w,int h){width=Math.max(1,w);height=Math.max(1,h);GLES30.glViewport(0,0,width,height);updateProjection();}
    @Override public void onDrawFrame(javax.microedition.khronos.opengles.GL10 gl){long now=System.nanoTime();float dt=lastNs==0?0:Math.min(.033f,(now-lastNs)/1_000_000_000f);lastNs=now;if(running&&dt>0)match.update(dt);int sky=match.skyColor;GLES30.glClearColor(Color.red(sky)/255f,Color.green(sky)/255f,Color.blue(sky)/255f,1);GLES30.glClear(GLES30.GL_COLOR_BUFFER_BIT|GLES30.GL_DEPTH_BUFFER_BIT);GLES30.glUseProgram(program);updateProjection();setupCamera();int fog=match.fogColor;GLES30.glUniform3f(uFogColor,Color.red(fog)/255f,Color.green(fog)/255f,Color.blue(fog)/255f);drawWorld();drawChests();drawPickups();drawBullets();drawEnemies();drawRemotePlayers();drawExtraction();drawPlayer();}
    private void updateProjection(){float fov=match.account().settings.fov-(match.aiming?12f:0f);Matrix.perspectiveM(projection,0,Math.max(50f,Math.min(100f,fov)),width/(float)height,.08f,125f);}
    private void setupCamera(){float fx=match.aimX,fz=match.aimZ;float rl=(float)Math.hypot(fx,fz);if(rl<.01){fx=0;fz=-1;}else{fx/=rl;fz/=rl;}float rx=-fz,rz=fx;float eyeX,eyeY,eyeZ,targetX,targetY,targetZ;if(match.firstPerson){eyeX=match.playerX+fx*.12f;eyeY=match.playerY+(match.crouched?1.55f:2.25f);eyeZ=match.playerZ+fz*.12f;targetX=eyeX+fx*8;targetY=eyeY-.05f;targetZ=eyeZ+fz*8;}else{float side=match.shoulderRight?1.15f:-1.15f;eyeX=match.playerX-fx*6.4f+rx*side;eyeY=match.playerY+(match.crouched?3.55f:4.8f);eyeZ=match.playerZ-fz*6.4f+rz*side;targetX=match.playerX+fx*1.4f;targetY=match.playerY+(match.crouched?1.0f:1.4f);targetZ=match.playerZ+fz*1.4f;}Matrix.setLookAtM(view,0,eyeX,eyeY,eyeZ,targetX,targetY,targetZ,0,1,0);Matrix.multiplyMM(vp,0,projection,0,view,0);GLES30.glUniform3f(uCamera,eyeX,eyeY,eyeZ);}
    private void drawWorld(){draw(cube,0,-.16f,0,NativeMatch.WORLD*2+.5f,.32f,NativeMatch.WORLD*2+.5f,match.groundColor,0,0,0);for(int i=0;i<34;i++){float x=-38+(i*17%77),z=-37+(i*29%75);if(Math.hypot(x-match.playerX,z-match.playerZ)<3)continue;draw(cylinder,x,1.05f,z,.48f,2.1f,.48f,0xff6b4931,0,0,0);draw(cone,x,3.05f,z,2.7f,4.0f,2.7f,match.treeColor,0,0,0);}for(int i=0;i<24;i++){float x=-36+(i*23%73),z=-35+(i*31%71);draw(sphere,x,.38f,z,1.55f,.75f,1.2f,match.rockColor,i*17,0,0);}for(int i=0;i<10;i++){float x=-30+(i*13%61),z=-28+(i*19%57);draw(cube,x,.7f,z,1.5f,1.4f,1.5f,0xff9b6a3f,i*15,0,0);draw(cube,x,.72f,z,1.58f,.10f,1.58f,0xffd5a15d,i*15,0,0);}draw(cube,0,.02f,-NativeMatch.WORLD,84,.25f,.35f,0x8863dff5,0,0,0);draw(cube,0,.02f,NativeMatch.WORLD,84,.25f,.35f,0x8863dff5,0,0,0);draw(cube,-NativeMatch.WORLD,.02f,0,.35f,.25f,84,0x8863dff5,0,0,0);draw(cube,NativeMatch.WORLD,.02f,0,.35f,.25f,84,0x8863dff5,0,0,0);draw(cylinder,0,4.2f,-10,.9f,8.4f,.9f,0xff74543b,0,0,0);draw(cone,0,8.7f,-10,5.3f,3.2f,5.3f,0xffb65d4d,0,0,0);}
    private void drawChests(){for(NativeMatch.Chest c:match.chests){int col=c.opened?0xff61584e:0xffb8874d;draw(cube,c.x,.45f,c.z,1.15f,.82f,.82f,col,0,0,0);draw(cube,c.x,.72f,c.z,1.18f,.12f,.86f,0xffffd36f,0,0,0);}}
    private void drawPickups(){for(NativeMatch.Pickup p:match.pickups){NativeGameData.Item item=NativeGameData.ITEMS.get(p.itemId);int color="moonberry".equals(p.itemId)?0xffa491ff:item!=null&&"epic".equals(item.rarity)?0xff8e82ff:item!=null&&"rare".equals(item.rarity)?0xff63dff5:0xffffd36f;draw(sphere,p.x,.48f,p.z,.46f,.46f,.46f,color,0,0,0);draw(sphere,p.x,.48f,p.z,.78f,.78f,.78f,(color&0x00ffffff)|0x33000000,0,0,0);}}
    private void drawBullets(){int color=match.weapon().color;for(NativeMatch.Bullet b:match.bullets)draw(sphere,b.x,b.y,b.z,.15f,.15f,.15f,color,0,0,0);}
    private void drawEnemies(){for(NativeMatch.Enemy e:match.enemies){float yaw=(float)Math.toDegrees(Math.atan2(match.playerX-e.x,-(match.playerZ-e.z)));SpeciesCatalog3D.Species s=SpeciesCatalog3D.ALL[Math.floorMod(e.species,8)];drawCritter(e.x,0,e.z,yaw,s,.92f,false);}}
    private void drawRemotePlayers(){for(NativeMatch.RemotePlayer r:match.remotePlayers.values()){if(r==null)continue;SpeciesCatalog3D.Species s=SpeciesCatalog3D.ALL[SpeciesCatalog3D.indexOf(r.species)];float yaw=(float)Math.toDegrees(Math.atan2(match.playerX-r.x,-(match.playerZ-r.z)));drawCritter(r.x,0,r.z,yaw,s,1f,false);draw(cylinder,r.x,3.45f,r.z,.06f,.45f,.06f,0xff7ef7d4,0,0,0);}}
    private void drawPlayer(){if(match.firstPerson){Point w=local(match.playerX,match.playerZ,yawDeg(),match.shoulderRight?.28f:-.28f,.72f);drawWeapon(w.x,match.playerY+(match.crouched?1.25f:1.7f),w.z,yawDeg(),match.weapon());return;}SpeciesCatalog3D.Species s=SpeciesCatalog3D.ALL[SpeciesCatalog3D.indexOf(match.account().speciesId)];drawCritter(match.playerX,match.playerY,match.playerZ,yawDeg(),s,match.crouched?.82f:1f,true);}
    private void drawExtraction(){for(int i=0;i<16;i++){double a=i*Math.PI*2/16;float x=match.extractX+(float)Math.sin(a)*2.7f,z=match.extractZ+(float)Math.cos(a)*2.7f;draw(cube,x,.07f,z,.45f,.14f,.90f,0xffffd36f,(float)Math.toDegrees(a),0,0);}draw(cylinder,match.extractX,3.8f,match.extractZ,.18f,7.5f,.18f,0x99ffd36f,0,0,0);draw(sphere,match.extractX,7.4f,match.extractZ,.65f,.65f,.65f,0xffffd36f,0,0,0);}
    private void drawCritter(float x,float y,float z,float yaw,SpeciesCatalog3D.Species s,float scale,boolean player){int body=s.bodyColor(),accent=s.accentColor(),paw=s.pawColor(),vest=s.vestColor();draw(sphere,x,y+1.16f*scale,z,1.30f*scale,1.55f*scale,1.02f*scale,body,yaw,0,0);draw(sphere,x,y+1.30f*scale,z-.08f*scale,1.05f*scale,.92f*scale,.86f*scale,vest,yaw,0,0);Point head=local(x,z,yaw,0,.05f*scale);draw(sphere,head.x,y+2.31f*scale,head.z,1.20f*scale,1.05f*scale,1.03f*scale,body,yaw,0,0);Point muzzle=local(x,z,yaw,0,.52f*scale);draw(sphere,muzzle.x,y+2.18f*scale,muzzle.z,.66f*scale,.45f*scale,.64f*scale,paw,yaw,0,0);for(int side:new int[]{-1,1}){Point eye=local(x,z,yaw,side*.27f*scale,.49f*scale);draw(sphere,eye.x,y+2.48f*scale,eye.z,.11f*scale,.14f*scale,.09f*scale,0xff0b1217,yaw,0,0);}drawEars(x,y,z,yaw,s,scale,body,accent);drawLimbs(x,y,z,yaw,s,scale,body,paw);drawTail(x,y,z,yaw,s,scale,body,accent);Point wp=local(x,z,yaw,.58f*scale,.28f*scale);NativeGameData.Weapon gun=player?match.weapon():new ArrayList<>(NativeGameData.WEAPONS.values()).get(Math.floorMod(s.id.hashCode(),NativeGameData.WEAPONS.size()));drawWeapon(wp.x,y+1.52f*scale,wp.z,yaw,gun);}
    private void drawEars(float x,float y,float z,float yaw,SpeciesCatalog3D.Species s,float scale,int body,int accent){if("none".equals(s.ears))return;for(int side:new int[]{-1,1}){Point q=local(x,z,yaw,side*.40f*scale,.03f*scale);if("floppy".equals(s.ears))draw(cylinder,q.x,y+2.62f*scale,q.z,.25f*scale,.80f*scale,.24f*scale,accent,yaw,0,side*28);else if("triangle".equals(s.ears)||"upright".equals(s.ears)||"bat".equals(s.ears)||"horn".equals(s.ears)||"antler".equals(s.ears))draw(cone,q.x,y+2.86f*scale,q.z,.43f*scale,.85f*scale,.43f*scale,accent,yaw,0,side*12);else draw(sphere,q.x,y+2.67f*scale,q.z,.42f*scale,.42f*scale,.35f*scale,accent,yaw,0,0);}}
    private void drawLimbs(float x,float y,float z,float yaw,SpeciesCatalog3D.Species s,float scale,int body,int paw){for(int side:new int[]{-1,1}){Point arm=local(x,z,yaw,side*.62f*scale,.12f*scale);draw(cylinder,arm.x,y+1.25f*scale,arm.z,.25f*scale,.92f*scale,.25f*scale,"wing".equals(s.limb)?s.accentColor():body,yaw,0,side*18);Point foot=local(x,z,yaw,side*.35f*scale,.18f*scale);draw(sphere,foot.x,y+.32f*scale,foot.z,.48f*scale,.35f*scale,.62f*scale,paw,yaw,0,0);}}
    private void drawTail(float x,float y,float z,float yaw,SpeciesCatalog3D.Species s,float scale,int body,int accent){if("none".equals(s.tail))return;Point q=local(x,z,yaw,.12f*scale,-.70f*scale);if("puff".equals(s.tail)||"stub".equals(s.tail)||"bear".equals(s.tail))draw(sphere,q.x,y+1.05f*scale,q.z,.48f*scale,.48f*scale,.48f*scale,accent,yaw,0,0);else if("beaver".equals(s.tail))draw(cube,q.x,y+.86f*scale,q.z,.72f*scale,.22f*scale,1.10f*scale,accent,yaw,24,0);else draw(cylinder,q.x,y+1f*scale,q.z,.30f*scale,1.25f*scale,.30f*scale,"brush".equals(s.tail)?body:accent,yaw,55,18);}
    private void drawWeapon(float x,float y,float z,float yaw,NativeGameData.Weapon w){int color=w==null?0xff75d06f:w.color;draw(cube,x,y,z,.28f,.28f,1.12f,color,yaw,0,0);Point b=local(x,z,yaw,0,.70f);draw(cylinder,b.x,y,b.z,.15f,.66f,.15f,0xffdbe8ec,yaw,90,0);}
    private float yawDeg(){return (float)Math.toDegrees(Math.atan2(match.aimX,-match.aimZ));}private Point local(float x,float z,float yaw,float lateral,float forward){double r=Math.toRadians(yaw);float rx=(float)Math.cos(r),rz=(float)Math.sin(r),fx=(float)Math.sin(r),fz=-(float)Math.cos(r);return new Point(x+rx*lateral+fx*forward,z+rz*lateral+fz*forward);}
    private void draw(MeshFactory3D.Mesh mesh,float x,float y,float z,float sx,float sy,float sz,int color,float yaw,float pitch,float roll){Matrix.setIdentityM(model,0);Matrix.translateM(model,0,x,y,z);Matrix.rotateM(model,0,yaw,0,1,0);Matrix.rotateM(model,0,pitch,1,0,0);Matrix.rotateM(model,0,roll,0,0,1);Matrix.scaleM(model,0,sx,sy,sz);Matrix.multiplyMM(mvp,0,vp,0,model,0);GLES30.glUniformMatrix4fv(uMvp,1,false,mvp,0);GLES30.glUniformMatrix4fv(uModel,1,false,model,0);GLES30.glUniform4f(uColor,Color.red(color)/255f,Color.green(color)/255f,Color.blue(color)/255f,Color.alpha(color)/255f);mesh.positions.position(0);mesh.normals.position(0);GLES30.glEnableVertexAttribArray(aPos);GLES30.glVertexAttribPointer(aPos,3,GLES30.GL_FLOAT,false,0,mesh.positions);GLES30.glEnableVertexAttribArray(aNormal);GLES30.glVertexAttribPointer(aNormal,3,GLES30.GL_FLOAT,false,0,mesh.normals);GLES30.glDrawArrays(GLES30.GL_TRIANGLES,0,mesh.vertexCount);}
    public void setRunning(boolean v){running=v;lastNs=0;}public void setInput(float mx,float mz,float lx,float lz){match.setMove(mx,mz);match.setLook(lx,lz);}public void setFireHeld(boolean v){match.setFireHeld(v);}public void setAiming(boolean v){match.setAiming(v);}public void setInteracting(boolean v){match.setInteracting(v);}public void fireOnce(){match.fireOnce();}public void reload(){match.reload();}public void jump(){match.jump();}public void toggleCrouch(){match.toggleCrouch();}public void heal(){match.heal();}public void toggleCamera(){match.toggleCamera();}public void toggleShoulder(){match.toggleShoulder();}
    public String status(){return match.account().displayName+" • "+match.mapName+" • "+match.networkMode+"\n"+match.weapon().name+"  HP "+Math.round(match.hp)+"  SH "+Math.round(match.shield)+"  Berries "+match.moonberries+"/5\n"+match.objectiveTitle()+" • "+match.objectiveDetail();}public float hp(){return match.hp;}public float shield(){return match.shield;}public int loot(){return match.moonberries;}public int petals(){return match.store.active().petals;}public int medkits(){return match.medkits();}public int bandages(){return match.bandages();}public float playerX(){return match.playerX;}public float playerZ(){return match.playerZ;}public float extractX(){return match.extractX;}public float extractZ(){return match.extractZ;}public float matchSeconds(){return match.matchTime;}public String speciesName(){NativeGameData.Species s=NativeGameData.SPECIES.get(match.account().speciesId);return s==null?"Puppy":s.name;}public String weaponName(){return match.weapon().name;}public String cameraName(){return match.firstPerson?"FIRST PERSON":"THIRD PERSON";}public boolean shoulderRight(){return match.shoulderRight;}public int magazine(){return match.mag;}public int reserveAmmo(){return match.reserveAmmo();}public String mapName(){return match.mapName;}public String objectiveTitle(){return match.objectiveTitle();}public String objectiveDetail(){return match.objectiveDetail();}public String interactionHint(){return match.interactionHint();}public String banner(){return match.banner;}public boolean primaryComplete(){return match.primary.complete;}public boolean bonusComplete(){return match.bonus.complete;}public String primaryTitle(){return match.primary.title;}public String bonusTitle(){return match.bonus.title;}public boolean ended(){return match.ended;}public boolean extracted(){return match.extracted;}public List<NativeProfileStore.Stack> backpack(){return new ArrayList<>(match.backpack);}public int networkPlayers(){return match.networkPlayerCount();}public String networkMode(){return match.networkMode;}
    private static int buildProgram(String vs,String fs){int v=shader(GLES30.GL_VERTEX_SHADER,vs),f=shader(GLES30.GL_FRAGMENT_SHADER,fs),p=GLES30.glCreateProgram();GLES30.glAttachShader(p,v);GLES30.glAttachShader(p,f);GLES30.glLinkProgram(p);int[] ok=new int[1];GLES30.glGetProgramiv(p,GLES30.GL_LINK_STATUS,ok,0);if(ok[0]==0)throw new IllegalStateException("OpenGL program link failed: "+GLES30.glGetProgramInfoLog(p));GLES30.glDeleteShader(v);GLES30.glDeleteShader(f);return p;}private static int shader(int type,String source){int s=GLES30.glCreateShader(type);GLES30.glShaderSource(s,source);GLES30.glCompileShader(s);int[] ok=new int[1];GLES30.glGetShaderiv(s,GLES30.GL_COMPILE_STATUS,ok,0);if(ok[0]==0)throw new IllegalStateException("OpenGL shader failed: "+GLES30.glGetShaderInfoLog(s));return s;}private static final class Point{final float x,z;Point(float x,float z){this.x=x;this.z=z;}}
    private static final String VS="#version 300 es\nprecision mediump float;\nin vec3 aPos;in vec3 aNormal;uniform mat4 uMvp;uniform mat4 uModel;out vec3 vNormal;out vec3 vWorld;void main(){vec4 world=uModel*vec4(aPos,1.0);vWorld=world.xyz;vNormal=mat3(uModel)*aNormal;gl_Position=uMvp*vec4(aPos,1.0);}";private static final String FS="#version 300 es\nprecision mediump float;\nin vec3 vNormal;in vec3 vWorld;uniform vec4 uColor;uniform vec3 uCamera;uniform vec3 uFogColor;out vec4 outColor;void main(){vec3 n=normalize(vNormal);vec3 lightDir=normalize(vec3(.35,.82,.25));float raw=max(dot(n,lightDir),0.0);float toon=raw>.72?1.0:(raw>.36?.78:.56);vec3 viewDir=normalize(uCamera-vWorld);float rim=pow(1.0-max(dot(n,viewDir),0.0),2.0)*.22;float dist=distance(vWorld,uCamera);float fog=clamp((dist-38.0)/46.0,0.0,.72);vec3 base=uColor.rgb*(toon+rim);outColor=vec4(mix(base,uFogColor,fog),uColor.a);}";
}
