apply plugin: 'com.android.application'

android {
    namespace 'com.harleytg.critterextraction'
    compileSdk 35

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.setSrcDirs(['src/main/java'])
            res.setSrcDirs(['res'])
            assets.setSrcDirs(['../assets'])
            jniLibs.setSrcDirs(['libs'])
        }
    }

    defaultConfig {
        applicationId 'com.harleytg.critterextraction'
        minSdk 34
        targetSdk 35
        versionCode 200001
        versionName '0.2.0-native-test1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/robovm/ios/robovm.xml', 'META-INF/DEPENDENCIES.txt', 'META-INF/DEPENDENCIES',
                         'META-INF/dependencies.txt', '**/*.gwt.xml']
            pickFirsts += ['META-INF/LICENSE.txt', 'META-INF/LICENSE', 'META-INF/license.txt',
                           'META-INF/LGPL2.1', 'META-INF/NOTICE.txt', 'META-INF/NOTICE', 'META-INF/notice.txt']
        }
    }
}

configurations { natives }

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-arm64-v8a"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi-v7a"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86_64"
}

tasks.register('copyAndroidNatives') {
    doFirst {
        file('libs/armeabi-v7a').mkdirs()
        file('libs/arm64-v8a').mkdirs()
        file('libs/x86_64').mkdirs()
        configurations.natives.copy().files.each { jar ->
            def outputDir = null
            if (jar.name.endsWith('natives-armeabi-v7a.jar')) outputDir = file('libs/armeabi-v7a')
            if (jar.name.endsWith('natives-arm64-v8a.jar')) outputDir = file('libs/arm64-v8a')
            if (jar.name.endsWith('natives-x86_64.jar')) outputDir = file('libs/x86_64')
            if (outputDir != null) {
                copy {
                    from zipTree(jar)
                    into outputDir
                    include '*.so'
                }
            }
        }
    }
}

tasks.matching { it.name.contains('merge') && it.name.contains('JniLibFolders') }.configureEach {
    dependsOn 'copyAndroidNatives'
}
