(() => {
  'use strict';
  const codes = {
    BOOT_JS:'CE-BOOT-JS-001', BOOT_FILE:'CE-BOOT-FILE-001', BOOT_TIMEOUT:'CE-BOOT-TIMEOUT-001',
    WEB_404:'CE-WEB-404', WEB_403:'CE-WEB-403', WEB_500:'CE-WEB-500',
    NET_OFFLINE:'CE-NET-OFFLINE-001', NET_TIMEOUT:'CE-NET-TIMEOUT-001',
    ASSET_MISSING:'CE-ASSET-MISSING-001', ASSET_INVALID:'CE-ASSET-INVALID-001',
    RENDER_WEBGL:'CE-RENDER-WEBGL-001', RENDER_CANVAS:'CE-RENDER-CANVAS-001',
    SAVE_PARSE:'CE-SAVE-PARSE-001', SAVE_WRITE:'CE-SAVE-WRITE-001',
    ACCOUNT_IMPORT:'CE-ACCOUNT-IMPORT-001', ACCOUNT_DUPLICATE:'CE-ACCOUNT-DUPLICATE-001',
    MULTI_HOST:'CE-MULTI-HOST-001', MULTI_JOIN:'CE-MULTI-JOIN-001', MULTI_SIGNAL:'CE-MULTI-SIGNAL-001', MULTI_WEBRTC:'CE-MULTI-WEBRTC-001',
    AI_STATE:'CE-AI-STATE-001', UI_DIALOG:'CE-UI-DIALOG-001', PORTABLE_BUILD:'CE-PORTABLE-BUILD-001', UNKNOWN:'CE-UNKNOWN-001'
  };
  window.CritterErrorCodes = Object.freeze(codes);
})();
