(() => {
  'use strict';
  const S=window.CritterSecurityRuntime;if(!S)return;
  const FIELDS=[['securityIds','Security ID'],['installHashes','Install hash'],['profileFingerprints','Profile fingerprint'],['usernames','Username'],['recruitCodes','Recruit code'],['accountIdHashes','Account ID hash']];
  function style(){if(document.getElementById('critterSecurityStyles'))return;const e=document.createElement('style');e.id='critterSecurityStyles';e.textContent=`
#critterSecurityCenter .modal-card{max-width:1040px}.critter-security-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.critter-security-panel{padding:16px;border:1px solid var(--control-border,rgba(255,255,255,.14));border-radius:16px;background:var(--control-bg,rgba(0,0,0,.2))}.critter-security-panel h3{margin:0 0 12px}.critter-security-identity>div,.critter-security-row{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:9px 0;border-bottom:1px solid rgba(255,255,255,.09)}.critter-security-identity code{max-width:68%;overflow-wrap:anywhere;text-align:right}.critter-security-row:last-child,.critter-security-identity>div:last-child{border-bottom:0}.critter-security-row div{min-width:0}.critter-security-row small{display:block;overflow-wrap:anywhere;opacity:.8}.critter-security-status{display:flex;flex-wrap:wrap;gap:10px;align-items:center;margin:10px 0}.critter-security-actions{display:flex;flex-wrap:wrap;gap:8px}.critter-security-form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.critter-security-form label{display:grid;gap:5px}.critter-security-form .span-2{grid-column:1/-1}.critter-security-list{max-height:270px;overflow:auto}.critter-security-wide{grid-column:1/-1}@media(max-width:760px){.critter-security-grid{grid-template-columns:1fr}.critter-security-wide{grid-column:auto}.critter-security-form{grid-template-columns:1fr}.critter-security-form .span-2{grid-column:auto}.critter-security-identity>div{display:grid}.critter-security-identity code{max-width:100%;text-align:left}}
`;document.head.append(e);}
  function toast(message){const t=document.getElementById('toast');if(!t)return;t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}
  async function copy(value,message){const text=String(value);const fallback=()=>{const a=document.createElement('textarea');a.value=text;a.style.cssText='position:fixed;opacity:0';document.body.append(a);a.select();document.execCommand('copy');a.remove();};try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(text);else fallback();}catch(_){fallback();}toast(message);}
  function download(){const report=S.report(),blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`critter-security-report-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200);S.log('security-report-exported',{events:report.events.length,localBans:report.localBans.length});}
  function center(){let d=document.getElementById('critterSecurityCenter');if(d)return d;style();d=document.createElement('dialog');d.id='critterSecurityCenter';d.className='modal';d.innerHTML=`<div class="modal-card wide"><header><div><span class="eyebrow">FAIR PLAY • HOST BANS • GLOBAL BANS</span><h2>Security Center</h2></div><button class="icon-close" type="button">×</button></header><p class="modal-intro">Multiplayer uses host-authoritative Fair Play and non-invasive profile identifiers. It does not collect IP addresses, hardware serial numbers, files, or unrelated browser data.</p><div class="critter-security-status"></div><div class="critter-security-actions"><button class="secondary copy-security" type="button">Copy Identity JSON</button><button class="secondary export-security" type="button">Export Security Report</button><button class="ghost refresh-security" type="button">Refresh Global Bans</button></div><div class="critter-security-grid"><section class="critter-security-panel"><h3>Current Account Identity</h3><div class="critter-security-identity"></div></section><section class="critter-security-panel"><h3>Add Host-Local Ban</h3><form class="critter-security-form"><label>Identifier type<select name="type">${FIELDS.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>Duration<select name="duration"><option value="86400000">24 hours</option><option value="604800000">7 days</option><option value="2592000000">30 days</option><option value="permanent">Permanent</option></select></label><label class="span-2">Identifier<input name="value" maxlength="120" required placeholder="Paste the exact identifier"></label><label class="span-2">Reason<input name="reason" maxlength="180" required value="Cheating or repeated Fair Play violations"></label><button class="primary span-2" type="submit">Add Host Ban</button></form></section><section class="critter-security-panel"><h3>Active Host Bans</h3><div class="critter-security-list local-bans"></div></section><section class="critter-security-panel"><h3>Recent Security Events</h3><div class="critter-security-list security-events"></div></section><section class="critter-security-panel critter-security-wide"><h3>Important Limitation</h3><p>This static peer-to-peer browser edition can stop normal evasion and casual cheating, but a determined user can clear storage, edit XML, or run modified game code. Server-grade global enforcement requires owner-controlled authentication and a dedicated authoritative backend.</p></section></div><footer><button class="primary close-security" type="button">Done</button></footer></div>`;document.body.append(d);
    d.querySelector('.icon-close').onclick=d.querySelector('.close-security').onclick=()=>d.close();d.querySelector('.copy-security').onclick=()=>copy(JSON.stringify(S.identity(),null,2),'Security identity copied');d.querySelector('.export-security').onclick=download;d.querySelector('.refresh-security').onclick=async e=>{e.currentTarget.disabled=true;await S.loadRemote();e.currentTarget.disabled=false;render();};
    d.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),type=S.text(f.get('type'),32),raw=S.text(f.get('value'),120),value=type==='usernames'?raw.toLowerCase():type==='recruitCodes'?raw.toUpperCase():raw,reason=S.text(f.get('reason'),180)||'Host ban',duration=String(f.get('duration'))==='permanent'?null:Number(f.get('duration')),identifiers=Object.fromEntries(FIELDS.map(([k])=>[k,[]]));if(!identifiers[type]||!value)return;identifiers[type]=[value];S.addBan({identifiers,reason,durationMs:duration,source:'manual'});e.currentTarget.querySelector('[name=value]').value='';render();};return d;}
  function row(root,title,detail,button){const r=document.createElement('div');r.className='critter-security-row';const info=document.createElement('div'),strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=title;small.textContent=detail;info.append(strong,small);r.append(info);if(button)r.append(button);root.append(r);}
  function render(){const d=document.getElementById('critterSecurityCenter');if(!d)return;const id=S.identity(),remote=S.remote(),identityRoot=d.querySelector('.critter-security-identity');identityRoot.innerHTML='';[['Security ID',id.securityId||'Not created yet'],['Install hash',id.installHash],['Account ID hash',id.accountIdHash],['Profile fingerprint',id.profileFingerprint],['Username',id.username||'No username'],['Recruit code',id.recruitCode||'No recruit code']].forEach(([label,value])=>{const r=document.createElement('div'),s=document.createElement('strong'),c=document.createElement('code');s.textContent=label;c.textContent=value;r.append(s,c);identityRoot.append(r);});
    const status=d.querySelector('.critter-security-status');status.innerHTML='';const badge=document.createElement('span'),source=document.createElement('span'),self=S.find(id,{remoteOnly:true});badge.className='pill';badge.textContent=`${remote.bans.length} active global ban${remote.bans.length===1?'':'s'}`;source.textContent=`Source: ${remote.source}${remote.updatedAt?` • ${remote.updatedAt}`:''}${remote.error?` • ${remote.error}`:''}`;status.append(badge,source);if(self){const danger=document.createElement('span');danger.className='pill';danger.textContent=`This profile is globally restricted: ${self.id}`;status.append(danger);}
    const bans=d.querySelector('.local-bans');bans.innerHTML='';const list=S.localBans();if(!list.length)bans.textContent='No active host bans.';for(const ban of list.slice().reverse()){const b=document.createElement('button');b.className='danger-button';b.type='button';b.textContent='Unban';b.onclick=()=>{S.removeBan(ban.id);render();};const identifiers=Object.entries(ban.identifiers).filter(([,v])=>v.length).map(([k,v])=>`${k}: ${v.join(', ')}`).join(' | ');row(bans,ban.reason,`${ban.id} • ${ban.expiresAt?`expires ${new Date(ban.expiresAt).toLocaleString()}`:'permanent'} • ${identifiers}`,b);}
    const events=d.querySelector('.security-events');events.innerHTML='';const ev=S.events().slice(-50).reverse();if(!ev.length)events.textContent='No security events recorded yet.';for(const item of ev)row(events,item.type,`${new Date(item.at).toLocaleString()} • ${Object.entries(item.details||{}).map(([k,v])=>`${k}: ${v}`).join(' • ')}`);}
  function install(){const add=()=>{style();const top=document.querySelector('.top-actions');if(top&&!document.getElementById('securityCenterBtn')){const b=document.createElement('button');b.id='securityCenterBtn';b.className='ghost';b.type='button';b.textContent='Security';b.onclick=()=>{const d=center();render();if(!d.open)d.showModal();};const settings=top.querySelector('[data-open="settingsModal"]');settings?settings.after(b):top.prepend(b);}center();render();};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',add,{once:true}):add();}
  S.openCenter=()=>{const d=center();render();if(!d.open)d.showModal();};window.addEventListener('critter-security-change',render);install();
})();
