(() => {
  'use strict';
  const VERSION='1.0.0',DB_KEY='critterExtractionInventory',INSTALL_KEY='critterSecurityInstallIdV1',BANS_KEY='critterSecurityHostBansV1',EVENTS_KEY='critterSecurityEventsV1',CACHE_KEY='critterSecurityRemoteBanCacheV1';
  const nativeSet=Storage.prototype.setItem,nativeStringify=JSON.stringify;
  let internalWrite=false,remote={loaded:false,source:'none',updatedAt:'',bans:[],error:''},readyResolve;
  let ready=new Promise(resolve=>{readyResolve=resolve;});
  const root=(()=>{try{return document.currentScript?.src?new URL('../../',document.currentScript.src):new URL('./',location.href);}catch(_){return new URL('./',location.href);}})();
  const banUrl=new URL('security/bans.json',root).href;
  const text=(v,n=160)=>String(v??'').replace(/[<>\u0000-\u001f]/g,'').trim().slice(0,n);
  const parse=(v,f=null)=>{try{return JSON.parse(v);}catch(_){return f;}};
  const token=(prefix,bytes=16)=>{const a=new Uint8Array(bytes);if(globalThis.crypto?.getRandomValues)crypto.getRandomValues(a);else for(let i=0;i<a.length;i++)a[i]=Math.random()*256;return `${prefix}_${[...a].map(v=>v.toString(16).padStart(2,'0')).join('')}`;};
  const hash=value=>{const s=String(value||'');let a=0x811c9dc5,b=0x9e3779b9;for(let i=0;i<s.length;i++){const c=s.charCodeAt(i);a=Math.imul((a^c)>>>0,0x01000193)>>>0;b=Math.imul((b^(c+(i+1)*131))>>>0,0x85ebca6b)>>>0;b^=b>>>13;}return a.toString(16).padStart(8,'0')+b.toString(16).padStart(8,'0');};
  function rawSet(key,value){internalWrite=true;try{nativeSet.call(localStorage,key,value);}finally{internalWrite=false;}}
  function installId(){let id='';try{id=text(localStorage.getItem(INSTALL_KEY),96);}catch(_){}if(!/^csi_[a-f0-9]{24,64}$/i.test(id)){id=token('csi',18);try{rawSet(INSTALL_KEY,id);}catch(_){}}return id;}
  function secureDb(db){if(!db||!Array.isArray(db.accounts))return db;for(const a of db.accounts){if(!a||typeof a!=='object')continue;if(!/^csp_[a-f0-9]{24,64}$/i.test(String(a.securityId||'')))a.securityId=token('csp',18);if(!Number.isFinite(+a.securityCreatedAt)||+a.securityCreatedAt<=0)a.securityCreatedAt=Date.now();a.securityVersion=1;}return db;}
  function readDb(){try{const raw=localStorage.getItem(DB_KEY);if(!raw)return null;const db=secureDb(parse(raw));if(db)rawSet(DB_KEY,nativeStringify(db));return db;}catch(_){return null;}}
  function account(){const db=readDb();return db?.accounts?.find(a=>a?.id===db.activeId)||db?.accounts?.[0]||null;}
  function identity(value){if(value&&typeof value==='object'&&('securityId'in value||'installHash'in value))return {version:1,securityId:text(value.securityId,96).toLowerCase(),installHash:text(value.installHash,64).toLowerCase(),accountIdHash:text(value.accountIdHash,64).toLowerCase(),username:text(value.username,32).toLowerCase(),recruitCode:text(value.recruitCode,32).toUpperCase(),profileFingerprint:text(value.profileFingerprint,64).toLowerCase()};const a=account()||{},securityId=text(a.securityId,96).toLowerCase(),username=text(a.username,32).toLowerCase(),recruitCode=text(a.recruitCode,32).toUpperCase();return {version:1,securityId,installHash:hash(installId()),accountIdHash:a.id?hash(a.id):'',username,recruitCode,profileFingerprint:hash([securityId,recruitCode,username].join('|'))};}
  function readList(key,max=250){try{const v=parse(localStorage.getItem(key),'');return Array.isArray(v)?v.slice(-max):[];}catch(_){return[];}}
  function writeList(key,v,max=250){try{rawSet(key,nativeStringify((Array.isArray(v)?v:[]).slice(-max)));}catch(_){}}
  function log(type,details={}){const list=readList(EVENTS_KEY,200),clean={};for(const[k,v]of Object.entries(details))clean[k]=typeof v==='number'||typeof v==='boolean'?v:text(v,220);list.push({id:token('evt',8),at:new Date().toISOString(),type:text(type,48),details:clean});writeList(EVENTS_KEY,list,200);window.dispatchEvent(new Event('critter-security-change'));}
  const ids=value=>Array.isArray(value)?[...new Set(value.map(v=>text(v,96).toLowerCase()).filter(Boolean))].slice(0,100):[];
  function cleanBan(raw,source='remote'){if(!raw||typeof raw!=='object')return null;const i=raw.identifiers||{},ban={id:text(raw.id||token('ban',8),80),enabled:raw.enabled!==false,source:text(raw.source||source,32),scope:text(raw.scope||'multiplayer',32).toLowerCase(),reason:text(raw.reason||'Multiplayer access restricted.',240),createdAt:text(raw.createdAt,48),expiresAt:raw.expiresAt?text(raw.expiresAt,48):null,appealUrl:/^https?:\/\//i.test(String(raw.appealUrl||''))?String(raw.appealUrl).slice(0,500):'',identifiers:{securityIds:ids(i.securityIds),installHashes:ids(i.installHashes),accountIdHashes:ids(i.accountIdHashes),usernames:ids(i.usernames),recruitCodes:Array.isArray(i.recruitCodes)?[...new Set(i.recruitCodes.map(v=>text(v,32).toUpperCase()).filter(Boolean))]:[],profileFingerprints:ids(i.profileFingerprints)}};return Object.values(ban.identifiers).some(v=>v.length)?ban:null;}
  const expired=ban=>!!ban?.expiresAt&&Number.isFinite(Date.parse(ban.expiresAt))&&Date.parse(ban.expiresAt)<=Date.now();
  function matches(ban,idValue){if(!ban?.enabled||ban.scope!=='multiplayer'||expired(ban))return false;const id=identity(idValue),x=ban.identifiers||{};return !!((id.securityId&&x.securityIds?.includes(id.securityId))||(id.installHash&&x.installHashes?.includes(id.installHash))||(id.accountIdHash&&x.accountIdHashes?.includes(id.accountIdHash))||(id.username&&x.usernames?.includes(id.username))||(id.recruitCode&&x.recruitCodes?.includes(id.recruitCode))||(id.profileFingerprint&&x.profileFingerprints?.includes(id.profileFingerprint)));}
  const allLocal=()=>readList(BANS_KEY,250).map(v=>cleanBan(v,'host')).filter(Boolean);
  const local=()=>allLocal().filter(v=>!expired(v));
  function find(idValue,{remoteOnly=false}={}){const id=identity(idValue);return remote.bans.find(b=>matches(b,id))||(remoteOnly?null:local().find(b=>matches(b,id)))||null;}
  function addBan({identity:idValue,identifiers,reason='Host ban',durationMs=null,source='manual',code=''}={}){const id=identity(idValue||{}),i=identifiers||{securityIds:id.securityId?[id.securityId]:[],installHashes:id.installHash?[id.installHash]:[],accountIdHashes:id.accountIdHash?[id.accountIdHash]:[],usernames:id.username?[id.username]:[],recruitCodes:id.recruitCode?[id.recruitCode]:[],profileFingerprints:id.profileFingerprint?[id.profileFingerprint]:[]};const ban=cleanBan({id:token('hostban',10),enabled:true,source,scope:'multiplayer',reason,createdAt:new Date().toISOString(),expiresAt:durationMs==null?null:new Date(Date.now()+Math.max(60000,+durationMs||0)).toISOString(),identifiers:i},'host');if(!ban)return null;const list=allLocal();list.push(ban);writeList(BANS_KEY,list,250);log('host-ban-added',{banId:ban.id,reason:ban.reason,code,expiresAt:ban.expiresAt||'permanent'});return ban;}
  function removeBan(id){const before=allLocal(),after=before.filter(b=>b.id!==text(id,80));writeList(BANS_KEY,after,250);if(after.length!==before.length)log('host-ban-removed',{banId:id});return after.length!==before.length;}
  function autoBan(idValue,code){const id=identity(idValue),previous=allLocal().filter(b=>b.source==='fair-play'&&matches({...b,expiresAt:null},id)).length,offense=previous+1,duration=offense>=3?null:offense===2?604800000:86400000;return addBan({identity:id,reason:`Automatic Fair Play ban (${text(code||'FP-REMOVED',48)}). Offense ${offense}.`,durationMs:duration,source:'fair-play',code});}
  async function loadRemote(){ready=new Promise(resolve=>{readyResolve=resolve;});try{const r=await fetch(banUrl,{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const body=await r.text();if(body.length>1048576)throw new Error('ban list too large');const data=JSON.parse(body);if(+data.schemaVersion!==1||!Array.isArray(data.bans))throw new Error('unsupported ban schema');remote={loaded:true,source:'network',updatedAt:text(data.updatedAt||r.headers.get('last-modified'),48),bans:data.bans.map(v=>cleanBan(v,'remote')).filter(Boolean),error:''};rawSet(CACHE_KEY,nativeStringify({updatedAt:remote.updatedAt,bans:remote.bans}));log('remote-ban-list-loaded',{count:remote.bans.length});}catch(e){const c=parse(localStorage.getItem(CACHE_KEY));remote=c&&Array.isArray(c.bans)?{loaded:true,source:'cache',updatedAt:text(c.updatedAt,48),bans:c.bans.map(v=>cleanBan(v,'remote')).filter(Boolean),error:text(e?.message,160)}:{loaded:true,source:'unavailable',updatedAt:'',bans:[],error:text(e?.message,160)};log('remote-ban-list-fallback',{source:remote.source,error:remote.error});}finally{readyResolve(remote);window.dispatchEvent(new Event('critter-security-change'));}return remote;}
  function report(){return {type:'critter-extraction-security-report-v1',generatedAt:new Date().toISOString(),securityVersion:VERSION,identity:identity(),remote:{source:remote.source,updatedAt:remote.updatedAt,count:remote.bans.length,error:remote.error},localBans:local(),events:readList(EVENTS_KEY,200)};}
  function installHooks(){if(!JSON.stringify.__critterSecurityWrapped){function stringify(v,r,s){if(v&&typeof v==='object'&&Array.isArray(v.accounts)&&'activeId'in v)secureDb(v);return nativeStringify.call(JSON,v,r,s);}Object.defineProperty(stringify,'__critterSecurityWrapped',{value:true});JSON.stringify=stringify;}if(!Storage.prototype.setItem.__critterSecurityWrapped){function setItem(k,v){if(!internalWrite&&String(k)===DB_KEY){const db=secureDb(parse(String(v)));if(db)v=nativeStringify(db);}return nativeSet.call(this,k,v);}Object.defineProperty(setItem,'__critterSecurityWrapped',{value:true});Storage.prototype.setItem=setItem;}}
  installHooks();installId();readDb();loadRemote();
  const runtime={VERSION,banUrl,text,hash,identity,log,find,matches,localBans:local,allLocalBans:allLocal,addBan,removeBan,autoBan,loadRemote,remote:()=>remote,ready:()=>ready,events:()=>readList(EVENTS_KEY,200),report};
  window.CritterSecurityRuntime=runtime;
  window.CritterSecurity=Object.freeze({version:VERSION,remoteBanUrl:banUrl,ready:()=>ready,identity:()=>({...identity()}),findBan:v=>find(v||identity()),listRemoteBans:()=>remote.bans.map(v=>parse(nativeStringify(v))),listLocalBans:()=>local().map(v=>parse(nativeStringify(v))),addLocalBan:addBan,removeLocalBan:removeBan,events:runtime.events,reloadRemoteBans:loadRemote,stableHash:hash,report});
})();
