#!/usr/bin/env python3
"""Generate the self-contained START_HERE.html from canonical source files."""
from pathlib import Path
import base64, mimetypes, re, json

ROOT = Path(__file__).resolve().parents[1]
index = (ROOT / 'index.html').read_text(encoding='utf-8')
css = (ROOT / 'styles.css').read_text(encoding='utf-8')
game = (ROOT / 'js' / 'game.js').read_text(encoding='utf-8').replace('</script>', '<\\/script>')
model = (ROOT / 'assets' / 'models' / 'harleys-model-library.js').read_text(encoding='utf-8').replace('</script>', '<\\/script>')

def data_uri(path: Path) -> str:
    mime = mimetypes.guess_type(path.name)[0] or 'application/octet-stream'
    return f"data:{mime};base64," + base64.b64encode(path.read_bytes()).decode('ascii')

assets = {}
for path in sorted((ROOT / 'assets').rglob('*')):
    if path.is_file() and path.suffix.lower() not in {'.txt', '.js'}:
        key = 'assets/' + path.relative_to(ROOT / 'assets').as_posix()
        assets[key] = data_uri(path)

# Replace literal HTML asset references.
for key, uri in sorted(assets.items(), key=lambda kv: len(kv[0]), reverse=True):
    index = index.replace('./' + key, uri)

index = re.sub(r'<link rel="stylesheet" href="\./styles\.css"[^>]*>', lambda _m: '<style>\n' + css + '\n</style>', index)
index = re.sub(r'<script src="\./assets/models/harleys-model-library\.js"[^>]*></script>', '<script>\n' + model + '\n</script>', index)
asset_map = '<script>window.__CRITTER_EMBEDDED_ASSETS__=' + json.dumps(assets, separators=(',', ':')) + ';</script>'
index = re.sub(r'<script src="\./js/game\.js\?v=[^"]+"[^>]*></script>', lambda _m: asset_map + '\n<script>\n' + game + '\n</script>', index)
index = index.replace(' — Harley’s Studios</title>', ' — Portable Edition — Harley’s Studios</title>')
index = '<!-- Generated by tools/build_portable.py. Do not edit this file directly. -->\n' + index
(ROOT / 'START_HERE.html').write_text(index, encoding='utf-8')
print(ROOT / 'START_HERE.html')
